#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Spiffy
Version  : 0.46
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/I/IN/INGY/Spiffy-0.46.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/I/IN/INGY/Spiffy-0.46.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libspiffy-perl/libspiffy-perl_0.41-1.debian.tar.xz
Summary  : 'Spiffy Perl Interface Framework For You'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Spiffy-license
Requires: perl-Spiffy-man

%description
NAME
Spiffy - Spiffy Perl Interface Framework For You
SYNOPSIS
package Keen;
use Spiffy -Base;
field 'mirth';
const mood => ':-)';

%package license
Summary: license components for the perl-Spiffy package.
Group: Default

%description license
license components for the perl-Spiffy package.


%package man
Summary: man components for the perl-Spiffy package.
Group: Default

%description man
man components for the perl-Spiffy package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Spiffy-0.46
mkdir -p %{_topdir}/BUILD/Spiffy-0.46/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Spiffy-0.46/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Spiffy
cp LICENSE %{buildroot}/usr/share/doc/perl-Spiffy/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Spiffy.pm
/usr/lib/perl5/site_perl/5.26.1/Spiffy.pod
/usr/lib/perl5/site_perl/5.26.1/Spiffy/mixin.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Spiffy/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Spiffy.3
